src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints\Length;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username", message="Ce nom d'utilisateur existe déjà")
 * @UniqueEntity("email", message="Cet email est déjà utilisé")
 * @Vich\Uploadable
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $facebook_id;

    /**
     * @ORM\Column(type="string", length=55, unique=true)
     * @Assert\NotBlank
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $avatar;

    /**
    * NOTE: This is not a mapped field of entity metadata, just a simple property.
    * 
    * @Vich\UploadableField(mapping="user_avatar", fileNameProperty="avatar", size="avatarSize")
    * 
    * @var File|null
    */
    private $avatarFile;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $avatarSize;

     /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $code;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_banned;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $validation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validateLostPassword;


/***********
RELATIONSHIP 
***********/

    /**
     * ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user", cascade={"remove"})
     */
    private $articles;

    /**
    * @ORM\OneToMany(targetEntity="App\Entity\Vote", mappedBy="user", cascade={"remove"})
    */
    private $votes;

    /**
    * @ORM\OneToMany(targetEntity="App\Entity\Flag", mappedBy="user", cascade={"remove"})
    */
    private $flags;

    /**
     * ORM\OneToMany(targetEntity="App\Entity\Feedback", mappedBy="user", cascade={"remove"})
     */
    private $feedback;


    public function __construct() 
    {
        $this->is_banned = false;
        $this->validate = false; 
        $this->validateLostPassword = false; 
        $this->articles = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->flags = new ArrayCollection();
        $this->feedback = new ArrayCollection();
    }


/****************
SETTERS & GETTERS  
****************/

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the value of username
     */ 
    public function getViewUsername()
    {
        return $this->username;
    }

    /**
     * Set the value of username
     *
     * @return  self
     */ 
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }


    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get oRM/OneToMany(targetEntity="App/Entity/Article", mappedBy="user")
     */ 
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * Get the value of votes
     */ 
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Get the value of slug
     */ 
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set the value of slug
     *
     * @return  self
     */ 
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of is_banned
     */ 
    public function getIsBanned()
    {
        return $this->is_banned;
    }

    /**
     * Set the value of is_banned
     *
     * @return  self
     */ 
    public function setIsBanned($is_banned)
    {
        $this->is_banned = $is_banned;

        return $this;
    }

    /**
     * Get the value of validation
     */ 
    public function getValidation()
    {
        return $this->validation;
    }

    /**
     * Set the value of validation
     *
     * @return  self
     */ 
    public function setValidation($validation)
    {
        $this->validation = $validation;

        return $this;
    }

    /**
     * Get the value of validate
     */ 
    public function getValidate()
    {
        return $this->validate;
    }

    /**
     * Set the value of validate
     *
     * @return  self
     */ 
    public function setValidate($validate)
    {
        $this->validate = $validate;

        return $this;
    }

    /**
     * Get the value of facebook_id
     */ 
    public function getFacebook_id()
    {
        return $this->facebook_id;
    }

    /**
     * Set the value of facebook_id
     *
     * @return  self
     */ 
    public function setFacebook_id($facebook_id)
    {
        $this->facebook_id = $facebook_id;

        return $this;
    }

     /**
     * Get the value of avatar
     */ 
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Set the value of avatar
     *
     * @return  self
     */ 
    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar; 

    }

    /**
     * Get the value of avatarSize
     *
     * @return  int|null
     */ 
    public function getAvatarSize()
    {
        return $this->avatarSize;
    }

    /**
     * Set the value of avatarSize
     *
     * @param  int|null  $avatarSize
     *
     * @return  self
     */ 
    public function setAvatarSize($avatarSize)
    {
        $this->avatarSize = $avatarSize;

        return $this;
    }

    /**
     * Get nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  File|null
     */ 
    public function getAvatarFile()
    {
        return $this->avatarFile;
    }

    /**
     * Set nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @param  File|null  $avatarFile  NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  self
     */ 
    public function setAvatarFile($avatarFile)
    {
        $this->avatarFile = $avatarFile;

        return $this;
    }

    /**
     * Get the value of flags
     */ 
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Set the value of flags
     *
     * @return  self
     */ 
    public function setFlags($flags)
    {
        $this->flags = $flags;

        return $this;
    }

    /**
     * Get oRM\OneToMany(targetEntity="App\Entity\Feedback", mappedBy="user", cascade={"remove"})
     */ 
    public function getFeedback()
    {
        return $this->feedback;
    }

    /**
     * Get the value of code
     */ 
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set the value of code
     *
     * @return  self
     */ 
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of validateLostPassword
     */ 

src/Entity/Vote.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VoteRepository")
 */
class Vote
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $vote_value;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="votes")
     */
    private $article;

    /**
    * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="votes")
    */
    private $user; 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVoteValue(): ?int
    {
        return $this->vote_value;
    }

    public function setVoteValue(int $vote_value): self
    {
        $this->vote_value = $vote_value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of article
     */ 
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * Get the value of user
     */ 
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set the value of user
     *
     * @return  self
     */ 
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Set the value of article
     *
     * @return  self
     */ 
    public function setArticle($article)
    {
        $this->article = $article;

        return $this;
    }
}

src/Form/Type/UserType.php
<?php


namespace App\Form\Type;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Presta\ImageBundle\Form\Type\ImageType; 
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add(
            'username', 
            TextType::class,
            [
                'label' => "Nom d'utilisateur",
                'constraints' => [
                    new Length(["min" => 5, "minMessage" => "Veuillez entrer un nom d'utilisateur entre 5 et 50 caractères", "max" => 50, "maxMessage" => "Veuillez entrer un nom d'utilisateur entre 5 et 50 caractères"])
                    ]
            ]
        )
        ->add(
            'email',
            EmailType::class,
            [
                "label" => "Email",
                'invalid_message' => 'L\'adresse email n\'est pas valide',
                'constraints' => [
                   new Length(["max" => 100, "maxMessage" => "Veuillez entrer un email plus court"]),
                ]
                                
            ]
        )
        ->add(
            'plain_password', 
            RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'Les mots de passe ne correspondent pas',
                'mapped' => false,
                'options' => [
                    'attr' => 
                    ['class' => 'password-field']
                ],
                'required' => true,
                'first_options'  => [
                    'label' => 'Mot de passe'
                ],
                'second_options' => [
                    'label' => 'Confirmation de mot de passe'
                ],
                'constraints' => [
                new NotBlank(),
                new Length(["min" => 8, "minMessage" => "Veuillez entrer un mot de passe entre 8 et 16 caractères", "max" => 16, "maxMessage" => "Veuillez entrer un mot de passe entre 8 et 16 caractères"])
                ]
            ]
        )
        ->add('avatarFile', 
        ImageType::class, [
            'label' => 'Avatar (facultatif)',
            'enable_remote' => false,
            'max_width' => 200,
            'max_height' => 200, 
            'aspect_ratios' => [],
            'cropper_options'=> [
                'aspectRatio'=> 1,  
                'viewMode' => 1,
                'minCropBoxWidth' => 120, 
                'minCropBoxHeight' => 120,
            ],
            'preview_height' => 200, 
            'preview_width' => 200, 
            'upload_button_class' => 'btn w-75 ml-0 mt-1 btn-success',
            'save_button_class' => 'btn btn-success mx-0 w-25',
            'cancel_button_class' => 'btn btn-outline-secondary mx-0 w-25'    
        ])
        ->add('recaptcha', EWZRecaptchaType::class, array(
            'attr'        => array(
                'options' => array(
                    'theme' => 'light',
                    'type'  => 'image',
                    'size'  => 'normal'
                )
            ),
            'mapped'      => false,
            'constraints' => array(
                new RecaptchaTrue()
            )
        ))   
        ->add(
            'condition', 
            CheckboxType::class,
            [
                'mapped' => false,
                'required' => true,
                'label' => "J'accepte les conditions générales d'utilisations", 
                'help' => 'En cochant cette case, vous reconnaissez avoir lu nos <a href="/mention-legales">conditions générales d\'utilisation</a>',
                'help_html' => true,

            ]
        )
        ->add('Envoyer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/article_by_user.html.twig
{% extends 'base.html.twig' %}


{% block title %}{{ user.viewUsername }}{% endblock %}

{% block stylesheets %}
{{ parent() }}
{{ encore_entry_link_tags('article_by_category') }}
{{ encore_entry_link_tags('pagination') }}
{% endblock %}

{% block body %}

<div class="articleAuthor d-flex">
        {# Default avatar #}
        {% if user.avatar == 'defaultAvatar.jpg' %}
        <img class="avatarUser" src="{{ asset("build/images/" ~ user.avatar ) }}"
            alt="image represent avatarUser {{ user.viewUsername }}">
        {% else %}
        {# user avatar #}
        <img class="avatarUser" src="{{ asset("uploads/user/avatar/" ~ user.avatar ) }}"
            alt="image represent avatarUser {{ user.viewUsername }}">
        {% endif %}
        <div class="user-article-title">
            <p class="user-article-title-p">{{user.viewUsername}}</p>
        </div>
</div>


<!-- Container Cards -->
<div class="container container-custum row">


    {% for article in articles %}


    <div class="card card-custum col-sm-5">
        {# Default articleImage #}
            {% if article.image == null %}
            <img class="card img-fluid" src="{{ asset("build/images/" ~ article.categories.first.picture ) }} "
            alt="image represent category {{ article.categories.first.name }}">
            {% else %}
        {# user articleImage #}
            <img id="articleImageDetail" src="{{ asset("uploads/article/image/" ~ article.image ) }} "
            alt="image represent article">
            {% endif %}

        <div class="card-body card-body-custum">
            <h5 class="card-title card-title-custum">
                <a href="{{path('articleDetails', {'slug':article.slug})}}" class="link-custum">
                   {{article.title}} 
                </a>
            </h5>

            <button class="btn btn-secondary btn-sm dropdown-toggle category-btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Catégories
            </button>
            <div class="dropdown-menu">
                <ul class="card-text-category">
                    {% for category in article.categories %}
                        <li><a href="{{path('articleByCategory', {'slug':category.slug})}}" class="link-custum">
                            {{category.name}}
                        </a></li>
                    {% endfor %}
                </ul>
            </div>


            <p class="card-paragraph card-paragraph-summary">
                {{article.summary}} 
            </p>

            {% set sum = 0 %}

            {# Sum of votes for one article #}
            {% for votes in article.votes %}
            {% set sum = sum + votes.voteValue %}
            {% endfor %}

            {# If article have a vote #}
            {% if (sum != 0) %}

            {# average #}
            {% set average = sum / article.votes|length %}
            {% set noteName = 'Noté :' %}

            {% if (average|round == 1) %}
            {% set label = 'Médiocre' %}
            {% endif %}

            {% if (average|round == 2) %}
            {% set label = 'Pas mal' %}
            {% endif %}

            {% if (average|round == 3) %}
            {% set label = 'Bien' %}
            {% endif %}

            {% if (average|round == 4) %}
            {% set label = 'Super' %}
            {% endif %}

            {% if (average|round == 5) %}
            {% set label = 'Excellent' %}
            {% endif %}

            {# article haven't a vote #}
            {% else %}
            {% set noteName = '' %}
            {% set label = 'Non noté' %}
            {% endif %}

            
            <p class=" card-paragraph card-paragraph-note">
                {{noteName}} {{label}}
            </p>

            <div class="d-flex justify-content-center">
                <a href="{{path('articleDetails', {'slug':article.slug})}}" class="btn btn-primary btn-articleDetails">Lire la suite</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

<div class="pagination-custum">
{{ knp_pagination_render(articles) }}
</div>

{% endblock %}

{% block javascripts %}
{{ parent() }}
{{ encore_entry_script_tags('pagination') }}
{% endblock %}

templates/user/form_email_lost_password.html.twig
{% extends 'base.html.twig' %}


{% block title %}Mot de passe oublié{% endblock %}

{% block stylesheets %}
{{ encore_entry_link_tags('form') }}
{% endblock %}

{% block body %}

{% for message in app.flashes('lostPasswordNotSuccess') %}
<div class="alert text-center notFoundRequest ">
    {{ message }}
</div>
{% endfor %}

<div class="container container-form-custum">
    {{ form_start(form) }}



    <div class="block-form-custum">

        <h1 class="h4 mb-3 font-weight-normal text-center">Entrez votre adressse email</h1>

        <div class="col-12">
            {{ form_row(form.email)}}

        </div>

        <div class="mt-4 ml-4"
            style="transform:scale(0.80);-webkit-transform:scale(0.70);transform-origin:0 0;-webkit-transform-origin:0 0;">
            {% form_theme form '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig' %}

            {{ form_widget(form.recaptcha, { 'attr': {
                     'options' : {
                     'theme': 'light',
                     'type': 'image',
                     'size': 'normal'
                     },
                  } }) }}
        </div>



        <div class="col-12 validateBtn">
            {{ form_row(form.Envoyer) }}
        </div>
    </div>


    {{ form_end(form) }}





</div>


{% endblock %}

{% block javascripts %}


{{ encore_entry_script_tags('form') }}


{% endblock %}

templates/user/modify_password.html.twig
{% extends 'base.html.twig' %}


{% block title %}Modification du mot de passe{% endblock %}

{% block stylesheets %}
{{ parent()}}
{{ encore_entry_link_tags('form') }}
{% endblock %}

{% block body %}



<div class="container container-form-custum">
    {{ form_start(form) }}

    <div class="block-form-custum">

        <h1 class="h4 mb-3 font-weight-normal text-center">Modifier votre mot de passe</h1>

        {% if form.oldPassword is defined %}
        <div class="col-12 edit-password-input">
            {{ form_label(form.oldPassword)}}

            {# error old password #}
            {% for message in app.flashes('NotsuccessModifyPassword') %}
            <div class="w-100 oldPasswordNotFound">
                {{ message }}
            </div>
            {% endfor %}

            {{ form_widget(form.oldPassword)}}
        </div>
        {% endif %}


        <div class="col-12 edit-password-input">
            {{ form_row(form.plain_password)}}
        </div>

        

        <div class="col-12 validateBtn">
            {{ form_row(form.Modifier) }}
        </div>
    </div>


    {{ form_end(form) }}

</div>


{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}Inscription{% endblock %}

{% block stylesheets %}
{{ encore_entry_link_tags('form') }}
{{ encore_entry_link_tags('formSignup') }}
{% endblock %}

{% block body %}



<div class="container container-form-custum">
    {{ form_start(form) }}

    

    <div class="block-form-custum">

        <h1 class="h4 mb-3 font-weight-normal text-center">S'inscrire</h1>
        <div class="col-12">
            {{ form_row(form.username) }}

        </div>
        <div class="col-12">
            {{ form_row(form.email) }}

        </div>
        <div class="col-12">
            {{ form_row(form.plain_password) }}

        </div>
        {% form_theme form '@PrestaImage/form/bootstrap_4.html.twig' %}
       
        <div class="col-12"> 
            {{ form_row(form.avatarFile) }}  
        </div>

        
        <div class="col-12 mt-4 condition-signup">
            {{ form_row(form.condition) }}
        </div>
    
        <div class="mt-4 ml-4" style="transform:scale(0.80);-webkit-transform:scale(0.70);transform-origin:0 0;-webkit-transform-origin:0 0;">
            {% form_theme form '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig' %}
 
             {{ form_widget(form.recaptcha, { 'attr': {
                 'options' : {
                 'theme': 'light',
                 'type': 'image',
                 'size': 'normal'
                 },
              } }) }} 
         </div>
       

        <div class="col-12 validateBtn">
            {{ form_row(form.Envoyer) }}
        </div>
    </div>


    {{ form_end(form) }}

    

    

</div>


{% endblock %}

{% block javascripts %}


{{ encore_entry_script_tags('form') }}
{{ encore_entry_script_tags('formSignup') }}

{% endblock %}